### ISSUE TITLE
component blocks data-throughput from profile fields to database ?

### ISSUE THREAD

**Issue by onderzoekspraktijk** [lcdservices/CiviCRM-Group-Sync#6]
I am developing civicrm as part of a joomla (3.4.4) website for a client. I use your component CiviCRM-Group-Sync, which is a nice addition to the functionality of civicrm. Thank you for developing it!
However it now presents me with a problem. This is the problem:
Recently I updated the civicrm-component to the now latest version (4.6.9). At the frontend I publish a profile form that is used to register as a new contact/user on the site. After the update it stopped working.
As I am new to the civicrm component it took ages to find what is causing this.
It turns out to be your component: when I de-activate it, the error disappears.
When I turn it on again the error appears again.

The error is this:
After filling in the profile-form, and sending it, there are no data in the corresponding fileds inside civicrm. There are data in the corresponding data in the core-joomla usercomponent.
When I activate sending an email with the data from the form this e-mail gets send and contains all civicrm data.
I presume (speculate) that the plugin triggering the group sync somehow disrupts writing the data to the civicrm component.

**Comment by lcdservices** [comment]
I've pushed up a patch for this. Can you download the update, install, test, and verify?

**Comment by onderzoekspraktijk** [comment]
Yup: works okay again!
Thank you for the promt patch.
